#!/bin/bash

# this is a starter file for the actual config file (simply called config)

# Deploy location (where your website will be deployed)
export WEBSITE_DEPLOY_LOC="localhost:8080"

# set the location of the website source (frontend content)
export WEBSITE_SRC_LOC="deps/personal-website"

# set to a python executable that is on the PATH
export PYTHON_EXEC="python"

